-- JaneDuck Database Schema
-- PostgreSQL (Neon)
-- v2: Updated per DESIGN_DECISIONS.md §12

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. decks
-- ============================================================
CREATE TABLE IF NOT EXISTS decks (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name          TEXT NOT NULL,
  description   TEXT,
  level         INT CHECK (level BETWEEN 1 AND 4),
  card_count    INT DEFAULT 0,
  source        TEXT CHECK (source IN ('janeduck', 'quizlet', 'user')) DEFAULT 'janeduck',
  source_id     TEXT,
  owner_id      UUID,  -- NULL = system deck
  is_public     BOOLEAN DEFAULT true,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. cards
-- ============================================================
CREATE TABLE IF NOT EXISTS cards (
  id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  deck_id            UUID NOT NULL REFERENCES decks(id) ON DELETE CASCADE,

  word               TEXT NOT NULL,
  definition         TEXT NOT NULL,

  -- enriched metadata (nullable)
  part_of_speech     TEXT,
  pronunciation      TEXT,
  collocations       JSONB,           -- ["reluctant to + verb"]
  example_sentences  JSONB,           -- [{sentence, context}, ...]

  -- HIGH scaffold: pre-generated by LLM at seed time (§10)
  starter_templates  JSONB,           -- ["My friend is ___ when ___", ...]
  topic_hints        JSONB,           -- ["school", "family", ...]

  -- Phase 2+
  translations       JSONB,           -- {ko: null, zh: null, ms: null}

  -- system
  level              INT CHECK (level BETWEEN 1 AND 4),
  difficulty_band    TEXT CHECK (difficulty_band IN ('common', 'uncommon', 'advanced')),
  tags               JSONB,
  order_in_deck      INT DEFAULT 0,
  source             TEXT CHECK (source IN ('janeduck', 'quizlet', 'user')) DEFAULT 'janeduck',
  source_id          TEXT,

  created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cards_deck_id ON cards(deck_id);

-- ============================================================
-- 3. study_sessions  (defined before writing_attempts for FK)
-- ============================================================
CREATE TABLE IF NOT EXISTS study_sessions (
  id                     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                UUID NOT NULL,
  deck_id                UUID NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
  mode                   TEXT CHECK (mode IN ('quick_review', 'writing')),
  session_type           TEXT CHECK (session_type IN ('mixed', 'starred_only', 'weak_only')) DEFAULT 'mixed',
  status                 TEXT CHECK (status IN ('in_progress', 'completed', 'abandoned')) DEFAULT 'in_progress',

  cards_studied_count    INT DEFAULT 0,
  self_evaluations_count INT DEFAULT 0,
  writings_completed     INT DEFAULT 0,

  started_at             TIMESTAMPTZ DEFAULT NOW(),
  last_active_at         TIMESTAMPTZ DEFAULT NOW(),
  ended_at               TIMESTAMPTZ,

  created_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_sessions_user_id ON study_sessions(user_id);

-- ============================================================
-- 4. user_cards (SRS + mastery + three-signal state)
-- ============================================================
CREATE TABLE IF NOT EXISTS user_cards (
  user_id                UUID NOT NULL,
  card_id                UUID NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, card_id),

  -- Mastery signal: 0=untouched, 1~2=familiar, 3~4=productive, 5=mastered
  mastery_score          FLOAT DEFAULT 0 CHECK (mastery_score BETWEEN 0 AND 1),
  mastery_level          INT DEFAULT 0 CHECK (mastery_level BETWEEN 0 AND 5),

  -- Self-evaluation signal (independent from mastery)
  last_self_eval_rating  TEXT CHECK (last_self_eval_rating IN ('dont_know', 'unsure', 'know', 'know_well')),
  last_self_eval_at      TIMESTAMPTZ,

  -- Writing signal
  writing_attempts_count INT DEFAULT 0,
  last_writing_score     INT,
  last_writing_at        TIMESTAMPTZ,
  recent_scores          JSONB DEFAULT '[]',  -- last 3 ai_scores for mastery/scaffold decisions

  -- Scaffold state
  current_scaffold       TEXT CHECK (current_scaffold IN ('high', 'medium', 'low')) DEFAULT 'high',

  -- Star
  is_starred             BOOLEAN DEFAULT false,
  starred_at             TIMESTAMPTZ,

  -- Stats
  review_count           INT DEFAULT 0,
  self_eval_count        INT DEFAULT 0,

  -- SRS (Hybrid SM-2) — algorithm detail in SRS_SPEC.md (Q6)
  srs_state              TEXT CHECK (srs_state IN ('new', 'learning', 'review', 'relearning', 'mastered')) DEFAULT 'new',
  ease_factor            FLOAT DEFAULT 2.5 CHECK (ease_factor BETWEEN 1.3 AND 3.0),
  interval_days          INT DEFAULT 0 CHECK (interval_days BETWEEN 0 AND 365),
  previous_interval_days INT DEFAULT 0,
  lapse_count            INT DEFAULT 0,

  last_reviewed_at       TIMESTAMPTZ,
  next_review_at         TIMESTAMPTZ DEFAULT NOW(),

  last_rating            TEXT CHECK (last_rating IN ('again', 'hard', 'good', 'easy')),
  last_rating_source     TEXT CHECK (last_rating_source IN ('writing', 'self_eval')),

  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_cards_user_id ON user_cards(user_id);
CREATE INDEX IF NOT EXISTS idx_user_cards_next_review ON user_cards(user_id, next_review_at);
CREATE INDEX IF NOT EXISTS idx_user_cards_starred ON user_cards(user_id, is_starred);

-- ============================================================
-- 5. writing_attempts (all attempts, never updated, append-only)
-- ============================================================
CREATE TABLE IF NOT EXISTS writing_attempts (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id               UUID NOT NULL,
  card_id               UUID NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  session_id            UUID REFERENCES study_sessions(id),

  scaffold_used         TEXT CHECK (scaffold_used IN ('high', 'medium', 'low')) NOT NULL,
  is_master_challenge   BOOLEAN DEFAULT false,

  -- context shown to student
  reference_starter     TEXT,           -- HIGH: starter sentence shown to student
  prompt_topic          TEXT,           -- student's topic/situation prompt
  topic_used            TEXT,           -- LOW: topic selected from pool (for dedup + Phase 2)
  structure_guide_used  TEXT,           -- LOW: structure guide selected (reason/result/feeling/contrast)

  user_text             TEXT NOT NULL,

  -- AI evaluation (§8 groups A/B/C)
  ai_score              INT CHECK (ai_score BETWEEN 0 AND 10),
  ai_feedback           TEXT,           -- chat_message (Group A)
  ai_strengths          JSONB,          -- array of strings (Group C)
  ai_weakness_signals   JSONB,          -- array of strings (Group C)
  writing_rating        TEXT CHECK (writing_rating IN ('again', 'hard', 'good', 'easy')),
  used_target_word      BOOLEAN DEFAULT false,
  meaning_correct       BOOLEAN DEFAULT false,

  -- attempt chain
  attempt_number        INT DEFAULT 1,
  parent_attempt_id     UUID REFERENCES writing_attempts(id),

  created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_writing_attempts_user_card ON writing_attempts(user_id, card_id);
CREATE INDEX IF NOT EXISTS idx_writing_attempts_session ON writing_attempts(session_id);

-- ============================================================
-- updated_at trigger
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER decks_updated_at
  BEFORE UPDATE ON decks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER user_cards_updated_at
  BEFORE UPDATE ON user_cards
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
